title:              Blog
tagline:            on GitHub Pages
description:        Blog Entries for TRN478 A4
url:                http://haminthecoder.github.io

author:
  name:             Hamin Lee
  url:              https://linkedin.com/in/hamin-lee
  email:            hamin-lee@outlook.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
